# basic options
title: Amazin' Amazon Trends
author: Charlotte Friis Theisen, Sonia Alouni and Sourabh Lal
description: This Data Story is an exploration of trends in Amazon reviews as part of the course Applied Data Analysis at EPFL.

github_username:  sourabhlal
github_username:  charlottetheisen
github_username:  soniaalouni

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
