# basic options
title: Ada - blog
author: Charlotte Friis Theisen, Sonia Alouni and Sourabh Lal
description: On this site you will find a blog post with a data story as part of our final project for the ada course
github_username:  sourabhlal
github_username:  charlottetheisen
github_username:  soniaalouni

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
